
set(target "Pathfinder")
set(working_dir "C:/Projects/Main/pathfinding-visualizer")
set(src_and_dest_list
    "C:/Projects/Main/pathfinding-visualizer/ui/theme/qmldir"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/theme/qmldir"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/startNode.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/startNode.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/endNode.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/endNode.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/clean.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/clean.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/pause.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/pause.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/start.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/start.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/terminate.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/terminate.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/delete.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/delete.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/wall.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/wall.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/weight.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/weight.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/error.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/error.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/warning.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/warning.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/status.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/status.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/light.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/light.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/svgs/dark.svg"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/svgs/dark.svg"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/fonts/JetBrainsMono-Bold.ttf"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/fonts/JetBrainsMono-Bold.ttf"
    "C:/Projects/Main/pathfinding-visualizer/ui/assets/fonts/JetBrainsMono-Regular.ttf"
    "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/Pathfinding/ui/assets/fonts/JetBrainsMono-Regular.ttf"

)
set(timestamp_file "C:/Projects/Main/pathfinding-visualizer/build/WebAssembly_Qt_6_10_2_single_threaded-Debug/.qt/Pathfinder_res.txt")
