name: Qt WebAssembly Build & Deploy
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "3.1.50"
          actions-cache-folder: "emsdk-cache"

      - name: Install Qt Desktop (Host Tools)
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.2"
          host: "linux"
          target: "desktop"
          arch: "linux_gcc_64"
          modules: "qtdeclarative qtsvg"
          set-env: true
          dir: "${{ github.workspace }}/qt-host"

      - name: Install Qt WASM
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.2"
          host: "linux"
          target: "desktop"
          arch: "wasm_singlethread"
          set-env: true
          dir: "${{ github.workspace }}/qt-wasm"

      - name: Build Project
        run: |
          mkdir build && cd build
          ${{ github.workspace }}/qt-wasm/Qt/6.7.2/wasm_singlethread/bin/qt-cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT_HOST_PATH=${{ github.workspace }}/qt-host/Qt/6.7.2/gcc_64
          cmake --build . --parallel
          mv Pathfinder.html index.html

      - name: Deploy to Web Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dev/web
          publish_dir: ./build/
          force_orphan: true